### ISSUE TITLE
AttachmentPath in index

### ISSUE THREAD

**Issue by 7ohm7** [thundernest/import-export-tools-ng#111]
Hi Christopher,
you are doing a good job in developing this addon. This is not so much an issue as a question or a request for improvement. I use export emails with attachments associated with index.html. The path to the attachments is at the end of each email file, so my apps need to open each file and parse the plain text to get it. I assume that it would be easier and faster to get AttachmentPath right from thunderbird structure before exporting it, so I ask - is it possible to get it this way and add new column in index.html for AttachmentPath/Paths value?

Thank you. 
Mark

**Comment by cleidigh** [comment]
@7ohm7 
Thanks for the kudos!
I think I need more clarity on your issue.  I think I get the general idea, but the devil is in the details.
I am not sure if you have used/looked at one of the new features in 4.1.0 regarding both custom date formats as well as several other new filename features.  I added these based on several users requests.  The ability to define the naming format for both attachments and in-line images allows users to get both the message filename and the attachments to sort sequentially.
I'm wondering if this feature will help you , but again I need to understand better.
- what export format are you using?
- describe the workflow in a little more detail
- take a look at the built-in help  that covers the new filename options
@cleidigh

**Comment by 7ohm7** [comment]
Hi Chris,

sorry, I didn't fulfill my obligation - I have ImportExportTools NG version 4.1.0-b27, Thunderbird 68.8.0 32-bit, OS Win 6.1.7601 and I use export Plain text (with attachments) with HTML index. 

I just need to know the paths to the attachments for each message without having to open the exported message (where the path is indicated). I  have a simple application in PowerQuery (PQ, under Excel), which loads a table of messages into Excel and I wanted to see here also the paths to the attachments so I can create link to easily open them. Currently, I'm doing this by having PQ open each message and look for the string "Attachments-" at the end, extract the name of the folder&file from the text after it and then compose the full path. But it does not have to be stable in every case and not fast at large quantities.

Naming features are great, I noticed them. But I'm sorry, I don't see the function for changing the name of the attachment - I tried different combinations, but still attachments are saved classically as before, i.e. \Attachments-{n}\{original-name}. Maybe I'm losing something in the translation of the dialog box for options (I have Slovak locale). Could you please send me a small screenshot of the relevant part of the settings, thanks to which I will be able to set renaming pattern for the attachments?

If I can set renaming for the attachments, then it solves the whole request other way, but still perfectly. Thank you in advance.

**Comment by cleidigh** [comment]
@7ohm7 
okay good, I think my assumption was correct, with the ability to control naming of the attachments, you can easily create Excel formula f(messagename) = attachment name

First please ignore bad grammar/wording as I have to do everything by dictation be disabled, corrections are pain.

I have two screenshots below show the relevant parts of the new help. You will actually see them localized as I made a lot of effort to get all of the help completely localized.  I am curious to you ever see this help? You can get to it from the options page for filenames (?)
Also, there is a help menu entry on all menus.  The help us are not complete but I wanted to get the system in, any feedback would be great.

The configuration for attachment names is described in the second help screenshot.  Basic steps:
- Set a message filename scheme that suits your needs (lots of options here, think about sorting as well as date formats)
- The attachment naming options ARE NOT in the options dialog, that's why you could not find them unless you read the help.  Once I decide how to present them . they will be added next version.
- Using the config editor , set the following preferences to a format that is presumably the same as the main messaging , file naming , but with an identifier for attachments and also the inline
 images.
- I set them as follows:
extensions.importexporttoolsng.export.attachments.filename_extended_format = 
${subject}-${date}-Att-${index}

extensions.importexporttoolsng.export.embedded_attachments.filename_extended_format =
${subject}-${date}-Emb-${index}

- Now you will get formatting as the last screenshot
- I am sure there is a more appropriate format, but because you can do anything you want you practically have lots of choices

Please let me know this is clear enough, as well as any feedback, I'm pretty sure this should work for you.

![image](https://user-images.githubusercontent.com/25272315/82490914-eaf47680-9ab1-11ea-818d-5421fe558785.png)

![image](https://user-images.githubusercontent.com/25272315/82490955-ffd10a00-9ab1-11ea-83f5-0ab8e493df72.png)

![image](https://user-images.githubusercontent.com/25272315/82490983-0c556280-9ab2-11ea-80b5-de17e008eab7.png)

![image](https://user-images.githubusercontent.com/25272315/82491038-1b3c1500-9ab2-11ea-8638-88543029b14d.png)

**Comment by 7ohm7** [comment]
@cleidigh
Hi Chris, I feel like an idiot when the answer was in front of my nose. Of course I looked at the help, about 20 times but I always skipped the section on experimental features. Yes, of course that's it, and everything works wonderfully.

So maybe to conclude for other blind users like me :) - if you need to automate the retrieval of paths to attachments/emebedded, use the same rename pattern for messages as for attachments/embedded.

Thank you.

**Comment by cleidigh** [comment]
@7ohm7 
Excellent!  the fact that these are under experimental does not make obvious.  I just tried to get you didn't for another user, but could not do the work.  so now you are at least a second person taking advantage of this option so that's good!
Reviews on ATN appreciated!
Cheers
Christopher

**Comment by cleidigh** [comment]
Any comments on the localized help, does look pretty good?

**Comment by 7ohm7** [comment]
I just looked at the whole help as well as the dialog boxes and all context menus in Slovak and everything is completely fine, understandable and clear. 

So yes, look pretty good :)

**Comment by cleidigh** [comment]
@7ohm7 
Thanks for the very nice review!!
It's good to hear that they help is clear.  I set up a nice way to Google translate the entire pages but retain certain elements that should not be translated.
BTW one of the things so want to do in the future is to have a completely configurable index table format.  I would add other columns you could choose from.
First  I have to figure out some of the more problematic issues present. 
Pleasure working with you, and thanks for your help in the process.
@cleidigh

**Comment by 7ohm7** [comment]
@cleidigh
You're welcome :) That's the minimum what I can do, I respect people who have an idea and are fully dedicated to it. Trying to translate the add-on into all common languages is even more for me than I would expect :) Thank you very much for the information, and I look forward to further use. Should I need any help with testing, I'm available.
