### ISSUE TITLE
TB v68.10.0 import doesn't recognize mbox on Mac

### ISSUE THREAD

**Issue by ivalaginja** [thundernest/import-export-tools-ng#135]
I am using Thunderbird v68.10.0 on a MacOS Catalina 10.15.5. I have copied my Mail files from my old Mac and it has this file structure:
<img width="946" alt="Screenshot 2020-07-16 at 17 17 24" src="https://user-images.githubusercontent.com/29508965/87689263-4b3d2700-c788-11ea-8a9b-f44b23d4c8ec.png">

I would like to import this `Inbox.mbox` file, but when I navigate to `ImportExportTools NG` --> `Import mbox file` and then hit ok on `Import directly one or more mbox files`, the file browser opens but the `Open` button stays greyed out when I highlight the mbox file I want to import. How can I import these files correctly?

**Comment by ivalaginja** [comment]
This might also be connected to #90 but I am already trying to import to a local folder.

Instead of trying to import mbox on `Local Folders`, I have also tried creating a new local folder and using the option `ImportExportTools NG` --> `Import all messages form a directory`, which does let me pick the mbox file but when I hit `Open` nothing happens.

**Comment by ivalaginja** [comment]
I realized I still have access to the messages saved on the server so my problem was solved, so feel free to close this issue unless you want to dive into this more or have a solution.

**Comment by cleidigh** [comment]
@ivalaginja 
I'm glad you found a workaround.  The issue is that the final structure that OS X creates is not directly able to be imported because of the extra files and structure.  The extension expects a structure like:
Folder1
  mbox1
Folder2
  mbox2

Another user has major scripts to accomplish this:
https://github.com/thundernest/import-export-tools-ng/pulls
I really need to try and improve the help to include descriptions of the expected structure.
let me know if I can help in in the other way
@ivalaginja

**Comment by ivalaginja** [comment]
Ah, awesome! That explains it. Thank you for the follow up!
