### ISSUE TITLE
Exporting mails issue

### ISSUE THREAD

**Issue by PascalJ97** [thundernest/import-export-tools-ng#17]
Hello, I'm trying to export all Data and profiles from thunderbird 60.9.0 to import it in Thunderbird 68 on a new computer with this tool but every option I use doesn't work. If I try "Export all files" ( the option in the tools menu above the "profiles export"; I use it in italian, I don't know how it's called in english version) he creates a file and then deletes it before I can use it. Is there a solution for this problem or am I doing something wrong?

**Comment by cleidigh** [comment]
@PascalJ97 
Thanks for the issue report. I am sure you are not doing anything wrong. I have had several bugs affecting both import and export unfortunately.
I have been able to address each item as reported.  I have a beta that addresses several issues.
What version are you using?  You can download the beta From here:
https://github.com/thundernest/import-export-tools-ng/blob/master/xpi/import-export-tools-ng-4.0.4-b2-tb.xpi
I adjusted testing including profile export successfully.
Please report back if this fixes your problem, otherwise I will investigate.

**Comment by PascalJ97** [comment]
Hello, thanks for the answer.
I solved my problem copying all thunderbird folders with a live linux system to the destination computer and it worked but tonight I will try the beta so I can say you if it works, the version I used was the newest on the thunderbird add-on store but I don't know wich exactly it was, I will also check this tonight.

**Comment by cleidigh** [comment]
@PascalJ97 
Note I posted a beta 4.0.4 in the XPI folder
it's not submitted yet.

**Comment by cleidigh** [comment]
@PascalJ97 
Any update on this?
