### ISSUE TITLE
Using the Automated backup feature of ImportExportTools NG 

### ISSUE THREAD

**Issue by Al-NN4ZZ** [thundernest/import-export-tools-ng#187]
Hi Christopher,
I just recently started using this add-on. I used the OPTION setting to schedule a full and automated backup ( i.e. SAVE: Always all files) and it looks like it worked fine. So I have a full backup of the profile.

I couldn't find a description of how the various settings for the backup work, so have some questions.

Question 1: I would like to get a better understanding of the SAVE option for "just files modified after the last backup." What are the files named and how are they related? I have the "automatic folder name + date" feature set.

Question 2: how would I use these backup files to restore the data in the even of a crash or corrupted profile?

Question 3: What is the "modal" window option?

Question 4: Is there a manual with more details on the various backup options and how to use them in restoring data?

Regards, Al / NN4ZZ

![ImportExportTools NG for Backup](https://user-images.githubusercontent.com/75909196/101992541-1b844380-3c82-11eb-9477-109188c961c5.jpg)

**Comment by Al-NN4ZZ** [comment]
Another question: Is the Address Book included in the backup?

Thanks...Al

**Comment by cleidigh** [comment]
@Al-NN4ZZ 
thanks for transferring your questions it's really only possible to troubleshoot here!
I will do my best to answer your questions. I will also try to use this opportunity
to work on adding more info to the included help. I am pretty short in my responses 
voice dictation/coding is pretty slow due to my disability.

- backing up only changed files
this is a basic differential backup.  an example using one of my test profiles which has  tiny bit of mail was 70MB, a differential 7MB.  Delta is just the changed files, I honestly have not used this self.  normally we just do a restore of the full backup.  I think you manually have to overlay the partial backups.
- Modal dialog
because sometimes changes in 68/78 this is actually only working in non- modal mode
the dialogue does not Prevent other operations outside of Thunderbird
- the address books are saved

I will try and think of some more, ask any follow-up you  need
it would also be good to get your feedback on the built-in help ( which needs the backup notes added)
Christopher

**Comment by Al-NN4ZZ** [comment]
Christopher,
Thanks for the reply.   That answered several of my questions.

Regarding the built-in help:  My main interest in the add-on so far has been the automated backup in the OPTIONS menu.  I didn't see much in the HELP file in terms of those option descriptions or how to use the tool.  Especially around the incremental backups.     

Daily incremental backups would be a great feature if it can be relied on.  The space requirement for a full backup of my files is 7.5GB.  That would be a very large amount of space if  I did full daily backups daily for several months.  ( about 225 GB per month ! )   The incremental would likely be only a few MB per day.  I would like to hear from some users that have experience with that feature.   Especially around how to use the files to restore a system.   Do you know anyone using this feature or could suggest a good place/forum to find someone?

Regards, Al

**Comment by cleidigh** [comment]
@Al-NN4ZZ  
one thing I might suggest to look at issues here with the backup label (I recently did several things in this area) you could post a question to those people about their use.
cheers
Christopher

**Comment by Al-NN4ZZ** [comment]
Christopher,

I scanned for "backup" in the posts here but didn't find anything or any particular post that looked like it would be the place to ask the questions.  I decided to try posting a question to the mozilla support forum.    Will let you know if I learn anything. 

https://support.mozilla.org/en-US/questions/1317998

I have also been posting in the thunderbird forum on the Groups.io platform.

https://groups.io/g/thunderbird/topic/importexporttools_ng/78911425?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,78911425

Thanks...Al

**Comment by Al-NN4ZZ** [comment]
Christopher,
See the attached with more questions and an idea for restoring the backup files.

Questions about the "Save all mail files" feature.  And note that this feature does not appear in the HELP file. 

Question about the "Backup" feature

Question / Idea about restoring the backup files.  

Thanks...Al

![image](https://user-images.githubusercontent.com/75909196/102212926-f3742a80-3ea3-11eb-816e-cf289da11d91.png)

**Comment by Al-NN4ZZ** [comment]
Christopher,
Just FYI, I created a groups.io forum for ThunderbirdEmail users.  Would love to have you join if interested.  You can check it out here: 

https://groups.io/g/ThunderbirdEmail

And of course anyone interested in Thunderbird, add-ons, etc  is invited to join

...Al

**Comment by Al-NN4ZZ** [comment]
Christopher,
I wonder if there is a setting to remind you that an update is ready to be run.  It appears that when the scheduled backup is due, it only happens when you exit/close the program.  I often leave Thunderbird up and running for weeks at a time.  Only when I close it do I see the message telling me about a Backup is needed and asking if I want to do it.  

Ideally a pop up would tell me about the backup which I could do or dismiss.  It would be ideal to offer these options in the pop up.

- Dismiss the backup 
- Dismiss the backup and remind me in X hours
- Do the backup and restart Thunderbird
- Do the Backup and close Thunderbird

Still looking for input on the incremental restore use.  So far I have not be able to find anyone that uses it.  Also would like some feedback in the idea to add a RESTORE tab to the Options to guide us through the process.   (Questions from the earlier post above)

Thanks...Al

**Comment by merckxist** [comment]
Not trying to hijack this issue, but my problem is very similar. Let me know if it should be "separated".

I have been trying to get the Options>Backup scheduling feature to run an automated daily backup  in v10.0.4 (Tbird v78.6.0) without success. My observations:
- The backup ONLY happens if Tbird is manually "exited".
- If the Frequency is set to Backup on Exit, then that is the only time it happens.
- If the frequency is one of the other settings, then the backup only happens if the Last backup is not within the limit established by selected time period.
- This seems to indicate there is some limitation to performing a backup if Tbird is running.
- Regardless of the setting of Use a "modal" window, a widow appears on exit to permit/deny the backup operation if it is warranted by the Options>Backup scheduling configuration.
- Whatever level of automation might be suggested by the "scheduling" options, manual intervention is always necessary based on the "exit" required and the permit/deny popup window limitations.
- No matter the settings in Options>Backup scheduling, the standalone Backup option does not function.

If, indeed, the backup can only be done with Tbird closed, I would like to have the options suggested by @Al-NN4ZZ to include a backup/restart. An alternative, if an exit is required, would be a time-of-day that the exit/backup would happen so I could choose a time between computer sessions that would just mean I restart Tbird the next time I use the computer to check mail.

I, too, leave Tbird running for days on end, usually only interrupted by software updates that require a reboot. I have tried the "modified since last backup" which seems to work correctly, but have not tried a restore. My system approach to backups is a weekly image with daily incremental images, so my interest here is to capture a daily copy of a Tbird profile that is picked up by my system backup just as a second source for possible recovery. A couple of months ago I had a Windows update go  a bit sideways and when I recovered my system image, one of the Tbird accounts wasn't right and I ended up using ImportExportToolsNG to clean it up. So I like the addon, for sure, just would like a bit more convenience in its backup feature.

**Comment by Al-NN4ZZ** [comment]
merckxist,
No problem,  My experience with the backup is the same as you described and I would also like to do the same schedule of weekly full and daily incremental backups.   It does appear that the backup must occur when TB is not running so I would like to see a window, tab or alert pop up with the options noted above.   

My larger / more important questions are about applying the incremental backups to do the restore.   

Hopefully Christopher will have some time to address these questions at some point.  

Thanks...Al

**Comment by cleidigh** [comment]
@merckxist 
@Al-NN4ZZ 

Guys
happy New Year's!
I am just returning from a sprint upgrading PrintingTools NG
 (check it out for extra printing layout options)
keeping up with everything is becoming very tough so enhancements
these days are difficult.  I would like to separate out soon
the enhancement issue (additional scheduling options) from the
questions of operation.  how about we get clarity on the top level 
ideas and then it would be great if one of  you could create 
separate enhancement issue with the results.

Operation:
- put backup timing is checked at Thunderbird shut down
- if the exit time is with the hysteresis window and the
  backup time set up or Backup on exit is valid, then the user
  is asked if they want to do the backup 
- the backup has to run when the rest of Thunderbird is shut down
- currently there are no automatic operations
- restorations of backups has to be done manually since the program cannot be running

Enhancements (couples of my thoughts):
- add 2 backup 'cycle options'
- each of these two would be one of the current  types and still
  be performed upon user exit

the above would not be too large a effort
I would like to get your thoughts on that as well as
alternatives and secondary improvements
Christopher

**Comment by Al-NN4ZZ** [comment]
Christopher,
I submitted a new issue / idea for the automated backup alert.  

https://github.com/thundernest/import-export-tools-ng/issues/195

I would like to wait until I can get a better understanding of the process to restore the Full profile backup and then how to apply the incremental backups before suggesting any other idea related to that.   Restoring the full profile backup is understood, but I can figure out the process for applying one or more of the incremental backups.  Obviously you can just overwrite the profile with the smaller incremental files. 

Regards, Al / NN4ZZ  
al (at) nn4zz (dot) com

**Comment by cleidigh** [comment]
@Al-NN4ZZ 
Thanks!
I will comment separately on the enhancement.
I have not found anything in the past that the original author describes restoration.
I believe overlaying the incremental over the last full backup makes sense.

**Comment by Al-NN4ZZ** [comment]
Christopher wrote:  "I believe overlaying the incremental over the last full backup makes sense."

My full profile backup is about 7.5GB in size and it makes sense that restoring the profile would restore all of my account data, emails, folders etc as of that date.   Simply overwrite the active profile file with the backup. 

However if I overwrite the active PROFILE with one of the incremental files which is only about 300MB and only contains changes since the last FULL backup, I don't believe that would be good.  All of the other data ( 7GB+) plus in the profile would be lost.   I would expect there to be some other method to read and apply the changes from the incremental file to the profile.  

So far I have not been able to find anyone that has used the  Full & Incremental files to restore their profile.   With all of the ImportExportTools users out there I would hope someone has tested, used, and maybe documented this feature?  Just not sure how to get the message out to all of the users and ask for input. 

Thanks...Al

**Comment by Al-NN4ZZ** [comment]
This issue is being closed out...the incremental restore questions was re-created in issue #202 

Thanks...Al
