### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by J68R** [thundernest/import-export-tools-ng#20]
I just want to say thank you to the developer of this ongoing project.
Apologies if it is not the done thing but your work is very much appreciated.

**Comment by cleidigh** [comment]
@J68R 
Thank you very much !
Extension developers are almost entirely of volunteer group.  We love to hear from users , both the good in the bad.  I tried to react to bug reports quickly as possible as well as enhance requests.
Feel free to post any problems or requests here, that's what were here for.
If you want to, doing a review on the Thunderbird at on-site is great to.
Cheers
Christopher

**Comment by J68R** [comment]
You've really helped make a big difference, I had the perfect storm of computer misfortune recently.

Required a new motherboard following a computer failure, then discovered the system hard drive had also been corrupted which needed a reinstall. All this while requiring access to several important emails as in the process of moving house.

Then restored the system on new hardware only to discover the old thunderbird had been updated to 68 and the old import export addon no longer works with the new v68... started to expect the worst.

that's where import export tools ng and all your hard work has well and truly saved the day.

All my important emails and contacts are now fully restored from the old (import export tools) backup directory without any problems whatsoever.

again Christopher, thank you.

**Comment by cleidigh** [comment]
@J68R 
Well , you made my night!  Don't misunderstand me, I completely sympathize with the terrible sequence of events, after 52 years I have superbly had my own scenario simpler to yours - they suck!
However, I am extremely happy that the extension worked when you needed it  most.
It's especially good to hear considering I have received multiple bad reviews, some referencing legitimate bugs  (mainly due to changing Thunderbird) so it's great to hear you had no problems.
I am currently acting as the Thunderbird Extension Liaison (a volunteer team member).  As part of their role I am managing and taking over critical extensions.  Your scenario, as bad as it was, is a great example of why we need this.  But I also know what it's like to be totally reliant on your computer and email, I'm disabled so I have to do everything by voice which does nothing if I have to mess with the computer physically.  Everything is great when it works and a killer when it doesn't ;-)

Thank you again for your great words - and happy moving!
Christopher

**Comment by cleidigh** [comment]
@J68R 
Would you consider doing a review on the add-ons site?
Thanks!

**Comment by cleidigh** [comment]
@J68R 
Thanks again - cheers
