### ISSUE TITLE
Just Not Working

### ISSUE THREAD

**Issue by amandabee** [thundernest/import-export-tools-ng#308]
I'm hoping to have a locally searchable archive of a few retired gmail accounts. To that end I installed Thunderbird 91.7.0 on Ubuntu, and used Takeout to download archived `.mbox` files. 

I installed ImportExportTools NG from the extensions and it appears to be enabled. 
![image](https://user-images.githubusercontent.com/150791/158650915-67fbf0ac-21c6-4c2a-954f-6b6d203a03d4.png) but the model under the 🔧 glyph all appears to be about exporting, not importing. And under the "tools" menu I'm only seeing the old "Import ..." menu item, which has not changed. That brings up the Import Wizard: 

![image](https://user-images.githubusercontent.com/150791/158696366-ca45da91-b337-4c8c-ab83-320c23f8ee8f.png)

Which can't or won't import a straight `.mbox` file. I am sure I'm missing something basic, but how do I use the extension to import an `mbox` archive?

**Comment by prosacious** [comment]
Thia is almost the same problem that I experience.  Same version of TB on two different W10 systems.  Although the ImportExport Tools NG appears under extensions (as above) there is nothing under the help/tools menu.  Another tool downloaded and worked perfectly.

**Comment by prosacious** [comment]
After spending time looking for answers I found that if I right click on the Local folder icon I can see the import export tool NG.  No idea why it's there.  Now trying to make sense of the options that the tool presents.

**Comment by prosacious** [comment]
When you right click on the local folder you should get the import export NG tool.  I chose "Import mbox file" which took me to a menu labelled "Choose the import way" on which I selected the top option "Import directly one or more mbox files".  This opens a file select menu that you should use to navigate to where your mbox is stored.  I was a bit confused because I could not find a file with a file extension of .mbox.  It appears in this version of Thunderbird (and possibly other versions) that this file extension is not used.  The mbox files that I wanted to import were past received emails and past sent emails.  These are called "Inbox" and "Sent" and are located in the Mail folder which is your profile (there are a couple of explanations on the TB help pages that explain how to find your profile).  This selection should import the selected files in the right format.  Well, it did for me.  I shall now see if I can drag the files to where they are required,  If this is of help then that's wonderful.  If it isn't...

**Comment by prosacious** [comment]
missed out a word in my excitement at getting it to work!

**Comment by prosacious** [comment]
I just found that you can import your selected mbox file into Inbox or Local Folders.  Once the file is where you want it you can right click on it and rename it.
