### ISSUE TITLE
v4.0.4, TBird 68.2.1 (64) - nothing works at all.

### ISSUE THREAD

**Issue by shadowbottle** [thundernest/import-export-tools-ng#34]
o/

So title says most of it, anyway. I have an mbox I'm trying to import from a mac install, this is on MacOS Mojave 10.14.6. This is a completely clean install of Thunderbird - no accounts loaded in it, and all I wanted to do was import an mbox from a dead machine OS to rescue data. I have the mbox structure/files but it doesn't matter.

What's happening: After installing the extension, I go to Tools >> ImportExportTools NG >> and literally nothing I click here gives me any other options of file/folder selection windows. Nothing happens. Also, there appears to be an empty menu selection at the top of the list (image attached). Not sure what's going on here. I've tried disable/enable, uninstall/reinstall and the result is the same.

Any ideas are welcome! I'm probably missing something dead easy, so apologies in advance >_<
![Screen Shot 2019-11-03 at 4 02 50 PM](https://user-images.githubusercontent.com/175063/68093074-76c8ed00-fe57-11e9-8fdb-ae974bf6dbee.png)

**Comment by cleidigh** [comment]
@shadowbottle 
No apologies necessary!  I know this really needs a user guide because it's a fairly complex extension with a lot of options.  I adopted it when the original author abandoned it so I'm still playing catch-up.
But I made an issue for that just yesterday.

I develop exclusively under window since I need  disabled/dictation , my Mac doesn't to that well
I just upgraded the Thunderbird there to the latest and did a trial import.

From your comments above I think I understand that after you choose the import mbox option no dialogue appears, correct?  what you should see is below:
![image](https://user-images.githubusercontent.com/25272315/68094136-a08c0f00-fe6b-11e9-9d6e-ad396b5673e3.png)

One possible thought:  you said you created a brand-new profile, did you create at least a single account?  Without account folders the extension cannot import anything.  
I should probably add a warning for that.

I have tested mbox file which I just imported.  you can download it from here:
https://github.com/thundernest/import-export-tools-ng/blob/master/tests/import/AppleMail/INBOX.mbox/mbox
right-click on the raw button and you can save it

let me know if that works
Christopher

**Comment by shadowbottle** [comment]
Hello Christopher - thanks for the reply.
No, I had not added a single account. I was hoping account information would either be built by the mbox data or no account would need to be associated with it. The account associated with the mbox is no longer accessible, and I'd like to keep all the data local.

Please correct me if I'm wrong but it sounds like I'd have to add an account, and then import the mbox into this active account, which would (assuming IMAP) would then use a lot of bandwidth to copy the mbox files back up to the account I'd added for importing into?

Any way to avoid doing that? Thanks again!

**Comment by shadowbottle** [comment]
Hello Christopher - thanks for the reply.
No, I had not added a single account. I was hoping account information would either be built by the mbox data or no account would need to be associated with it. The account associated with the mbox is no longer accessible, and I'd like to keep all the data local.

Please correct me if I'm wrong but it sounds like I'd have to add an account, and then import the mbox into this active account, which would (assuming IMAP) would then use a lot of bandwidth to copy the mbox files back up to the account I'd added for importing into?

Any way to avoid doing that? Thanks again!

**Comment by shadowbottle** [comment]
Nevermind - it was absolutely about not having an account. I was able to import the mbox into a local folder after having an account added to T-bird. Thank you for your help.

**Comment by cleidigh** [comment]
Great
I was hoping that was it.  I was going to suggest to create a dummy one and storage and local folder
 reviews on ATN are always appreciated!
cheers
Christopher
