### ISSUE TITLE
Fail on accenctuated folder names

### ISSUE THREAD

**Issue by JLuc** [thundernest/import-export-tools-ng#342]
"Spam" folder is "Indésirable" on a french langage TB
and "Models" (mails to be used as prototypes) is "Modèles"
and "Sent mails" is "Envoyés".
These standard folder names have accents in french ... and dont export well :
when exported these are copied as
- "Ind_sirables", "Mod_les" files and "Envoy_s" files
- these are empty (=0 byte) files.

And export stops and is limited to very few folders.

**Comment by cleidigh** [comment]
@JLuc 
Thanks for the post.
Can you describe the type of export and what folders you were exporting.
Also the versions for os, tb and IETNG.
@cleidigh

**Comment by cleidigh** [comment]
@JLuc 
I am assuming you are exporting folders to mbox files perhaps at the account level with structure?
Your first issue with the accents  being replaced with '_' should be because the option "Use only alphanumeric characters for filenames" in French : 
Utiliser juste 'alphanumérique lors du simple exports de fichiers
This option replaces all non basic ascii characters with the underscore for compatability issues.

The exported structure may be related to something else I am working on.  I will wait for your further details on that.
@cleidigh

**Comment by JLuc** [comment]
thanks (and sorry for not replying earlier)

**Comment by cleidigh** [comment]
@JLuc 
No problem, glad you are set
@cleidigh
