### ISSUE TITLE
Option to import mbox missing entirely, only have import maildir

### ISSUE THREAD

**Issue by TokenRing** [thundernest/import-export-tools-ng#371]
This is on Windows, TB version 102.6.1 (release channel) and the current ImportExportTools extension.
![image](https://user-images.githubusercontent.com/10012384/210117524-9151726b-1e85-4ef1-87b7-a88cd96966b9.png)

As you can see from this screenshot, I only have "import maildir folder" - I don't even have an option to import an mbox file at all. Yes, by default new copies of thunderbird set their storage mode to 'maildir' by default - as a test, I tried setting my settings to "mbox" mode instead, then restarting Thunderbird - no change, it still continues to only offer the maildir import option. I uninstalled and reinstalled the add-on too, no change there either.

**Comment by cleidigh** [comment]
@TokenRing 
I am not sure where you found the change in the default storage type, but it is still mbox and I recommend using that.
IETNG does not have the ability to import mbox to an account using maildir.
From your post it still seems like the account is in maildir mode, otherwise you would see the mbox options.
@cleidigh

**Comment by TokenRing** [comment]
Yes - sorry - that seems to have worked. I didn't realize that mbox was still the default in Thunderbird but yes, after spinning up a test VM with a fresh TBird install on it, it is indeed still mbox. I was able to import an .mbox file without issue. Worked great. Thanks!
