### ISSUE TITLE
message export menu position

### ISSUE THREAD

**Issue by perler** [thundernest/import-export-tools-ng#425]
Would it be possible to put the export message menu entry somewhere else? Right now it's at the very bottom of the menu which can be awkward to reach on lower resolution screens especially when you need to do this quite often over the day. 
![image](https://github.com/thundernest/import-export-tools-ng/assets/623092/596d36ce-a7cf-4553-a368-c9a71c022a1c)
Alternatively, is it possible to assign a keyboard shortcut?

**Comment by cleidigh** [comment]
@perler 
Yes I agree completely!
I am assuming you are a long time user and noticed I completely redesigned the new menu structure, hopefully more logical and clean (and hopefully liked).
Part of the reason was having to switch to the web extension apis.
With the first beta I was immediately dismayed to see the IETNG entry at the bottom. I have to use low resolution and my eye gaze mouse for my disability doesn't easily get down there.
My hope is that there is a clever way to move this, but it will be a hack.
No promises, but I will try 
@cleidigh
