### ISSUE TITLE
importexporttoolsng.experimental.hot_keys

### ISSUE THREAD

**Issue by KSU-BLUM** [thundernest/import-export-tools-ng#440]
Does importexporttoolsng.experimental.hot_keys work on ThunderBird 115.2.3 with ImportExportTools NG v14.0.0-b8?

I have entered the following string under importexporttoolsng.experimental.hot_keys:
[{"id": "1", "key": "D", "modifiers": "control shift", "oncommand": "exportSelectedMsgs(0)", "contexts": "messenger"}, {"id": "2", "key": "Y", "modifiers": "control shift", "oncommand": "alert('hk2 all')", "contexts": "all"}]

I would have expected that selecting a message and hitting ctrl-shift-D would save it to the default save folder, and hitting ctrl-shift-Y anywhere whould bring up an alert. But nothing whatever happens, even after restarting TB

BTW: where can I find documentation about the argument to be passed to exportSelectedMsgs()?

Background: Our users need to save a currently selected message as eml to a certain folder for exporting the message to our DMS. We implemented a hotkey for that using AutoIt and simulating a user choosing the commend of ImportExportTools in the File menu. But that command is gone now, so we need another means to tie a key to a command for exporting a message as eml to a given directory.

**Comment by cleidigh** [comment]
@KSU-BLUM 
To be frank I was planning to deprecate this functionality.
Partly because I never heard from anyone using it and TBKeys has been out for a while including v115 support.
Also I was planning to release by beginning of the week and I am just buried.

That said I think after a look I can get shortcuts to work in 3pane and message tabs. V115 messes up the contexts and I also had to change exportSelectedMsgs to work with shortcuts even for TBKeys.
In fact I have one beta user doing just that.

Hopefully just the above will work for you.
Send me your shortcuts asap and I will post a test version here tomorrow.
Please respond ASAP because I don't want to hold the release for more than a couple days.

cheers
Christopher

**Comment by KSU-BLUM** [comment]
Thanks for this, Christopher, and for all the good work.

You ask me to send you my "shortcuts", but I don't really understand what you mean by that. Do you mean the string I entered in importexporttoolsng.experimental.hot_keys? As I wrote above, that string is

[{"id": "1", "key": "D", "modifiers": "control shift", "oncommand": "exportSelectedMsgs(0)", "contexts": "messenger"}, {"id": "2", "key": "Y", "modifiers": "control shift", "oncommand": "alert('hk2 all')", "contexts": "all"}]

Well, I don't need the second one, but the first one. I want a key to save the selected message as eml file in a predefined folder (not sure if exportSelectedMsgs(0) would do that because I haven't found the docs explaining what argument I should pass to exportSelectedMsgs()

And it does not necessarily have to be ctrl-shift-D.

(Alternatively, we could also solve the problem if the menu "Export Saved Messages As" with its submenu items were attached as a submenu item to the menu item "ImportExportTools NG" in TB's Tools menu.)

In the end, what I need is just a way to allow our users to hit a key in order to save the selected message as an eml into a predefined folder.

Best
Kurt

**Comment by cleidigh** [comment]
@KSU-BLUM 
Thanks for the quick response!
Ok according to your description I think I have your needs covered.

What I meant by shortcuts was the set of hot_key definitions you currently use. From above, it's just a single key for save to eml. Great, I have that functionality restored.

Concerning the pre-defined target folder:
- In options go to the Export directories tab, this is where you can define three different export target directories 
- For the destination of selected messages you want to enable and define the directory
- Now any time you do any selected message export, the messages will be saved to your predefined directory WITHOUT any save dialog
- Note this is for any export formats (eml, html, pdf)

Finally you asked about the parameters for exportSelectedMsgs():

These are possible parameter definitions:
```
/* Export types:
	0 = EML
	1 = HTML
	2 = Plain Text
	3 = MBOX
	4 = MBOX (append mode)
	5 = index (HTML)
	6 = index (CSV)
	7 = CSV (with body)
	8 = HTML with attachments
	9 = Plain Text with attachments
	*/
```
I think since I understand your needs I will probably just incorporate for b9.
Hopefully I can do this today or tomorrow.

Cheers
Christopher

**Comment by KSU-BLUM** [comment]
Wow, thanks Christopher. You rock.

Looking forward to B9. 

We are waiting to deploy TB 115.2.3 company-wide, and that's the thing that has prevented us from doing so. When will B9 be released? Do you have any prelim timeline?

Best
Kurt

**Comment by cleidigh** [comment]
@KSU-BLUM 
I like to rock for my users %-}

I should get b9 out today or tomorrow with the official v14 release into the review Q Monday or Tuesday, crossing fingers.
Thanks 
Christopher

**Comment by KSU-BLUM** [comment]
you 🪨 indeed (that's the rock emoji, haha)

**Comment by cleidigh** [comment]
@KSU-BLUM 
I don't know your timezone or your schedule, but if I built a test version in 20m or so would you be able to test now?
@cleidigh

**Comment by cleidigh** [comment]
@KSU-BLUM 
Test version 
https://github.com/thundernest/import-export-tools-ng/blob/v14.0.0/xpi/import-export-tools-ng-14.0.0-b8hk1-tb.xpi

@cleidigh

**Comment by KSU-BLUM** [comment]
I've tested it. And you know what? It works! Thanks!

you 🪨🪨🪨!

**Comment by cleidigh** [comment]
Kurt
Excellent!
Again thank for the quick testing!!
Now I know b9 will be good in this respect.
BTW I am going to remove the test xpi so copy locally as needed.
@cleidigh

**Comment by KSU-BLUM** [comment]
Thanks, fine. Copied it. But if B9 is released early next week, the IT dudes can grab that.

best
Kurt

**Comment by cleidigh** [comment]
yes when I post b9 it will be sticky.
I will flag you then.

**Comment by KSU-BLUM** [comment]
Any news on this? I understood that you'd release b9 soonish?

**Comment by cleidigh** [comment]
@KSU-BLUM 
I actually released v14 to the review Q last Monday, I was hoping it was going to be reviewed last week. It looks like it will be reviewed Monday so I am hoping for that.
Already found several things I broke %-(
I will post as soon as it's released.
@cleidigh
