### ISSUE TITLE
Unable to import (same files) after exporting

### ISSUE THREAD

**Issue by Mutazalhawash** [thundernest/import-export-tools-ng#450]
I had to move my website to a new host, therefore all the emails had to be transferred as well. therefore, I tried to use importExportTool NG's option > [_export folder with subfolders (with structure)_] and it worked properly ~though I see the exported files without any extension. 

currently, I am unable to import the exported emails through [_import messages_] or [_import all messages from a directory_ > _also from its subdirectories_]

**please help me solve this issue.**

**Comment by cleidigh** [comment]
@Mutazalhawash 
If I understand correctly you exported with : 
Folder Export (mbox) / Structured with Subfolders 

mbox exports have no extension by default.

To import this structure you use: 
Import mbox files / Individual mbox files (with sbd structure)
Then you choose your top mbox file 

Hope this helps, let me know.
@cleidigh

**Comment by Luclinuxer** [comment]
Good morning, first of all, thank you for the great application. I'm in need of help. I use the ImportExportTools NG 14.0.0 updated on October 4th (I use it on Debian, ImportExportTool installed on Thunderbird 115.3.1 (64 bits). After the routine system update, Thunderbir was updated and ImportExportTools NG 14.0.0 was different. I I was no longer able to export the entire structure of an email account, as I could before. So, I only exported the "incoming" folder. When I went to test whether the backup was working properly, by importing this "incoming" folder, the program warned me that the file was more than 4 gb and it didn't matter (something about java was written in the message). Can you help me with this? What to do, step by step? Thank you \o/

**Comment by Mutazalhawash** [comment]
hello, thanks a lot. 
the solution that you have suggested here seems to be working (on one mailbox only) because I receive an error ( _file larger than 4GB, skipping_ ) is there a way to import those files?

**Comment by cleidigh** [comment]
@Mutazalhawash 
Yes unfortunately this problem is created by Thunderbird limiting file access to under 4GB. I think I will have to implement some workaround. In the meantime here is a manual method.

Ok here is the manual method to get your large mbox into Thunderbird
I cannot guarantee anything, but I think it should work.

- create a new folder for import in Local Folders, I will refer to as F
- on the folder, right click and choose IETNG \ Open folder directory
- you should see the top level folders including F with no extension and a size of zero
- now close Thunderbird
- copy your mbox into the directory, note it has to have the same name as F
- windows will warn on overwrite, say ok
- restart Thunderbird
- the folder F will look empty
- right click on F and choose Folder properties
- within the dialog click Repair folder
- you should see Rebuilding summary in the status bar.
- exit the dialog and you should see your messages

Let me know your results
@cleidigh
