### ISSUE TITLE
Add date option to use ISO format YYYY-MM-DD HH:MM(:SS) - Index.html of export all msg

### ISSUE THREAD

**Issue by artofit** [thundernest/import-export-tools-ng#58]
Hello,
tested ImportExportTools NG  4.04 with TB 68.3.1

When one is Exporting All Msg in Folder in html, the index file generated date is in format d-m-yyyy h:m, for example "24/3/2014 7.33"
I request a change or an option to have date dumped into iso format YYYY-MM-DD HH:MM(:SS), so in my example
2014-03-24 07:33

thanks

**Comment by cleidigh** [comment]
@artofit 
Thanks, happy new year!
This sounds like a good addition  , probably pretty easy to do.  Because this extension has long history I would not want to change the historical behavior so I would add this as a second date option.
I am battling some pretty significant bugs I have to take care of first but I may be able to get it in the next Release.
Christopher

**Comment by artofit** [comment]
> I may be able to get it in the next Release.
This is excellent news.
Happy new year too.

**Comment by JF1313** [comment]
This is a follow-up to https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/reviews/1160440/

Thanks for the quick response and Happy New Year as well.

An option for a space with the date so it appears YYYY MM DD would be appreciated as well.

Thanks!

Jeffrey

**Comment by artofit** [comment]
**I would stick to the date & time iso format**, especially if you consider hours as some might then request PM/AM instead of 24hours.

[https://en.wikipedia.org/wiki/ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)
OR
have a display mask so that people can have:

YYYYMMDD HHMMSS
YYYY-MM-DD HHhMM:SS
YYYY/MM/DD HH:MM:SS
YYYY MM DD HH MM SS
etc.

**Comment by katerasrael** [comment]
> have a display mask so that people can have:
> 
> YYYYMMDD ZHHMMSS
> YYYY-MM-DD ZHHhMM:SS
> YYYY/MM/DD ZHH:MM:SS
> YYYY MM DD ZHH MM SS
> etc.

I would appreciate to have something like that. Why not use the same conventions as the linux 'date'-format?

**Comment by cleidigh** [comment]
@katerasrael 
I think I mentioned somewhere above this approach.  Just the various examples above indicate you have to go to a configurable date string.  Since there are several other filename options I'm pretty certain that this point I'm going to use a template string option where users can clearly define both position and format for prefix/suffix/metadata/date

I just have to fix my significant bugs first ;-(
@cleidigh

**Comment by cleidigh** [comment]
@artofit 
@katerasrael 
See #75  for beta pointer & notes.
You now I have complete control over the date as well as other things!

**Comment by cleidigh** [comment]
Added:
4.1.0
