### ISSUE TITLE
Not Exporting All accounts

### ISSUE THREAD

**Issue by spinthepilot** [thundernest/import-export-tools-ng#71]
Greetings all, I'm so pleased that this tool has been updated (I'd be sunk without and I too wish we could donate to the developer of the update) 

BUT when I export my whole profile as usual only some of the accounts are being exported. Any ideas please? Thanks in advance

**Comment by spinthepilot** [comment]
P.S. I'm exporting and importing the profile to keep 2 machines in syc with each other.

**Comment by cleidigh** [comment]
@spinthepilot 
Thanks for the support!
Because I have taken this extension over I lack historical information as well as detailed internal knowledge in certain areas.  The profile will export is something I have only done basic testing for the current version.  

Can you give me information on platform/versions as well as a few more specifics .
for instance do you care consistent results in terms of what is exported?
The profile export is pretty brut force and simple, mostly a deep Copy.  
@cleidigh

**Comment by spinthepilot** [comment]
Mea Culpa, it seems I got in a pickle with different profiles that I was not aware were being created. It appears to be working just fine now. Apologies!

**Comment by cleidigh** [comment]
@spinthepilot 
No apologies required!  Any issue resolved with another try is one less issue to fix!
I also really have to find the time to make a bit of a user guide, never enough time.
I will go ahead and close this, + reviews are always welcome!
Cheers
Christopher
