### ISSUE TITLE
Not clear if this is working for T'bird 68.6.0 (64-bit) Mac

### ISSUE THREAD

**Issue by Lightxwave** [thundernest/import-export-tools-ng#91]
Have installed but T'bird indicates add-on isn't up to date and clearly **_it doesn't work_** on my new Mac as yet. disappointed as I was trying to import mbox boxes from entourage on old Mac. So which version does this work for and if not for 68.6.0 (64-bit) - when will it be updated?
Thanks

**Comment by cleidigh** [comment]
@Lightxwave 
I have been working on the window side for the next update.  I just did a test on my OS X system 10.14 Mojave.  I did a fresh install from the website since I was testing beta prior.  it installed with no compatibility warnings.  I get the context Menus EtCetera .
Did you get any dialogueConsol_error_output_for_major_think_it_was_compatible?
Do you get the menus under tools and the folder side?
cheers
@Lightxwave

**Comment by Lightxwave** [comment]
many thanks for your quick comment - when it required restart I only restarted the program. Now I've restarted the Mac it has shown up and all worked fine for Entourage box import. Well done  for good and useful add-on.
